
package com.bolivariano.microservice.personapasms.consumeWS;

import java.util.ArrayList;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://localhost/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


   


    /**
     * Consulta de lista de un cliente en listas negras, empresas o paises, Actividad Econ�mica
     * 
     * @param tipoID
     * @param paisNacionalidadOtra1
     * @param paisNacionalidadOtra2
     * @param fechaNacimiento
     * @param numeroID
     * @param producto
     * @param idListaBusqueda
     * @param nombres
     * @param paisOtraResidencia1
     * @param emailPredeterminado
     * @param tipoEmpresa
     * @param codActEconomica
     * @param paisOtraResidencia2
     * @param usuario
     * @param paisNacimiento
     * @param apellidosNombreCompania
     * @param paisNacionalidad
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VerificaIDEnteAct", action = "http://localhost/VerificaIDEnteAct")
    @WebResult(name = "VerificaIDEnteActResult", targetNamespace = "http://localhost/")
    @RequestWrapper(localName = "VerificaIDEnteAct", targetNamespace = "http://localhost/", className = "localhost.VerificaIDEnteAct")
    @ResponseWrapper(localName = "VerificaIDEnteActResponse", targetNamespace = "http://localhost/", className = "localhost.VerificaIDEnteActResponse")
    public String verificaIDEnteAct(
        @WebParam(name = "TipoID", targetNamespace = "http://localhost/")
        int tipoID,
        @WebParam(name = "NumeroID", targetNamespace = "http://localhost/")
        String numeroID,
        @WebParam(name = "Nombres", targetNamespace = "http://localhost/")
        String nombres,
        @WebParam(name = "Apellidos_NombreCompania", targetNamespace = "http://localhost/")
        String apellidosNombreCompania,
        @WebParam(name = "Producto", targetNamespace = "http://localhost/")
        String producto,
        @WebParam(name = "Usuario", targetNamespace = "http://localhost/")
        String usuario,
        @WebParam(name = "EmailPredeterminado", targetNamespace = "http://localhost/")
        String emailPredeterminado,
        @WebParam(name = "PaisNacionalidad", targetNamespace = "http://localhost/")
        String paisNacionalidad,
        @WebParam(name = "PaisNacimiento", targetNamespace = "http://localhost/")
        String paisNacimiento,
        @WebParam(name = "PaisNacionalidadOtra1", targetNamespace = "http://localhost/")
        String paisNacionalidadOtra1,
        @WebParam(name = "PaisNacionalidadOtra2", targetNamespace = "http://localhost/")
        String paisNacionalidadOtra2,
        @WebParam(name = "PaisOtraResidencia1", targetNamespace = "http://localhost/")
        String paisOtraResidencia1,
        @WebParam(name = "PaisOtraResidencia2", targetNamespace = "http://localhost/")
        String paisOtraResidencia2,
        @WebParam(name = "FechaNacimiento", targetNamespace = "http://localhost/")
        String fechaNacimiento,
        @WebParam(name = "idListaBusqueda", targetNamespace = "http://localhost/")
        int idListaBusqueda,
        @WebParam(name = "CodActEconomica", targetNamespace = "http://localhost/")
        String codActEconomica,
        @WebParam(name = "TipoEmpresa", targetNamespace = "http://localhost/")
        String tipoEmpresa);



}
